#!/bin/bash
echo "Styles Géo2France CACHE"

echo "Configuration de mapproxy"
if [ ! -d /srv/mapproxy/www ]; then
	mkdir -p /srv/mapproxy/www
	mkdir -p /srv/mapproxy/cache_data
fi

chown mapproxy /srv/mapproxy/cache_data

cd /root
python config.py > /srv/mapproxy/mapproxy.yaml
status=$?
if [ $status != 0 ]; then
	echo "Erreur de configuration ($status)" > /dev/stderr
	env
	cat /etc/hosts
	ping -c 1 styles-wms
	exit 1
fi

mapproxy-util create --force -t wsgi-app -f /srv/mapproxy/mapproxy.yaml /srv/mapproxy/www/config.py

chmod a+x /srv/mapproxy/www/config.py

echo "Configuration apache"
cat >  /etc/apache2/conf-enabled/mapproxy.conf << EOF
WSGIScriptAlias /mapproxy /srv/mapproxy/www/config.py
WSGIDaemonProcess mapproxy user=mapproxy group=mapproxy processes=2 threads=4
WSGIProcessGroup mapproxy

<Directory /srv/mapproxy/www>
  Require all granted
</Directory>
EOF

echo "Démarre apache" 1>&2

/usr/sbin/apache2ctl -D FOREGROUND
